name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - "*.*.*"
      - "main"
  pull_request:
    branches:
      - "*"
permissions:
  contents: read
jobs:
  test:
    name: Test Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        env:
          DATABASE_TYPE: mysql
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test
          COOKIE_SECRET: test-secret
          TOKEN_SECRET: test-token-secret
        run: npm run test:ci

      # Upload test coverage reports to Coveralls
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        if: always()